;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-star
        org-self-insert-command
        paredit-forward-delete
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        symbol-overlay-put
        counsel-M-x
        ))
